version: '3'

services:

  api:
    build:
      context: ./craftbeer
      dockerfile: Dockerfile
    image: jorgem/craftbeer
    container_name: craftbeer
    env_file:
      - .env
    command: java -jar app.jar
    volumes:
      - ./craftbeer/src:/craftbeer/src
    ports:
      - 9000:9000
    expose:
      - 9000
    depends_on:
      - postgresql

  postgresql:
    container_name: licitacoes-database
    image: postgres:12.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
